### ISSUE TITLE
New diagonal control option doesn't do anything.

### ISSUE THREAD

**Issue by SegaSnatcher** [MiSTer-devel/Arcade-QBert_MiSTer#2]
When I enable it, the game controls the same as if its disabled.  Meaning diagonals are not taken into account.  It simply plays with the standard up, down, left, right controls in mind. You will especially notice it if you try to hit Up/Left or Up/Right diagonals.

**Comment by pcornier** [comment]
The diagonal option was supposed to map diagonals to horizontal and vertical by detecting simultaneous directions so there's no need to rotate the joystick anymore. I may have misunderstood the original idea. What is the expected behaviour?

**Comment by SegaSnatcher** [comment]
The expected behavior is that you move Q*Bert with diagonal controls only in that mode.   Meaning if I want to move Q*bert to a cube that is down and to the left of him then I hit down+left diagonal on the D-Pad and if I want to move Q*Bert to a cube that is up to the right of him I hit Up + Right diagonal on my D-Pad and etc.    Just like the orignal Joystick seen here. 

https://lh3.googleusercontent.com/proxy/Mhya8Y52kYb0qrOn9VWE3vn6hqsct17baET_8Y_v9s200L_vrk0QGgft82-M3pCD0A6KrtSYXWwvAO_kuEwhsVwdtjVv35eBnfNEjZSESODznXESWVs-q3WE-Dj7SFoNLORPw3iPeQYCmbNXfrpFkg

**Comment by SegaSnatcher** [comment]
As an example the SG-1000 port of Q*Bert does it right.  You can only move Q*Bert if you hit diagonal controls.  Simply hitting up, down, left or right is disabled and doesn't move him.  So you would need to disable that as well to get proper diagonals working.

**Comment by pcornier** [comment]
Thank you, I understand now 👍
I will push something tomorrow.

**Comment by SegaSnatcher** [comment]
Great, thanks.

**Comment by SegaSnatcher** [comment]
> Thank you, I understand now 👍
> I will push something tomorrow.


Unfortunately your new diagonal code didn't work, in fact you can't move Q*bert at all now when you enable diagonal joystick.   

Curious, do you personally test your code before releasing?   Maybe, best thing to do going forward is sending me a test build until the diagonal control code works right.  Also, if you need help with it, maybe Alan will consider helping you. He does a lot of Arcade work on the MiSTer.

**Comment by pcornier** [comment]
Did you try to map your joystick config in MiSTer? It works very well on my side.

**Comment by SegaSnatcher** [comment]
I'll try to remap and see if that changes things.    I remapped in the actual Q*bert core, but not MiSTer itself.

**Comment by SegaSnatcher** [comment]
I remapped in MiSTer and still I get no movement when I enable diagonal joystick.   Q*bert only moves when I disable it.

What controller are you using?

**Comment by pcornier** [comment]
A classic 8BitDo. I tested with dpad and joystick, both are working well.

**Comment by pcornier** [comment]
Just to check that you are using the latest version, do you see the VFlip option?

**Comment by SegaSnatcher** [comment]
Yes, Vflip is working well.

**Comment by SegaSnatcher** [comment]
This issue has been solved.  Thanks pcornier.
