### ISSUE TITLE
Issue with Qbert's possition on cubes

### ISSUE THREAD

**Issue by Swainy101** [MiSTer-devel/Arcade-QBert_MiSTer#9]
Since the last Qbert update, the sprites no longer stand in the correct position of the cubes (they should stand in the middle of a cube) but instead stand towards the top left of a cube.
![qbert](https://user-images.githubusercontent.com/91020104/133932018-89ca55a1-f126-4c02-9a20-ec06d1e08dae.jpg)

**Comment by pcornier** [comment]
It should be fixed with the new release. It was a bad implementation of the vertical flip option.

**Comment by Swainy101** [comment]
Cool, it’s a favourite of mine so I’m very thankful of your hard work on
this.
